# Default Kibana Configuration (from Kibana base image)
# https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
server.name: kibana # Kibana 서버의 이름 설정
server.host: "0" # Kibana 서버가 수신 대기할 호스트 지정 ("0"은 모든 IP 주소를 의미)
elasticsearch.hosts: [ "http://elasticsearch:9200" ] # Kibana가 연결할 Elasticsearch 호스트 설정
xpack.monitoring.ui.container.elasticsearch.enabled: true # 컨테이너 환경에서 실행되는 Kibana의 X-Pack 모니터링 UI가 Elasticsearch를 사용해 데이터를 가져오도록 설정

# X-Pack security credentials
elasticsearch.username: elastic # Elasticsearch에 연결할 때 사용할 사용자 이름 설정
elasticsearch.password: elastic # Elasticsearch에 연결할 때 사용할 암호 설정