version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.17.10
    volumes:
      - type: bind # 호스트 시스템의 Elasticsearch 구성 파일을 컨테이너 내부로 바인딩하고 읽기 전용으로 설정
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume # Elasticsearch의 data 디렉토리를 볼륨에 마운트해 데이터를 영구적으로 저장
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # 호스트의 9200번 HTTP 포트를 Elasticsearch 컨테이너의 9200번 HTTP 포트에 매핑 (호스트 시스템에서 Elasticsearch의 REST API에 접근)
      - "9300:9300"  # 호스트의 9300번 TCP 포트를 Elasticsearch 컨테이너의 9300번 TCP 포트에 매핑 (호스트 시스템과 Elasticsearch 클러스터의 노드 간 통신)
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"  # Elasticsearch JVM의 최대 힙 크기와 최소 힙 크기 설정
      ELASTIC_PASSWORD: elastic  # Elasticsearch의 기본 비밀번호 설정
      discovery.type: single-node  # 단일 노드 탐색을 사용해 Elasticsearch 실행, 프로덕션 모드 비활성화 (https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html)
    networks:
      - elk  # elk 네트워크에 서비스 연결

  logstash:
    image: logstash:7.17.10
    volumes:
      - type: bind # 호스트 시스템의 Logstash 구성 파일을 컨테이너 내부로 바인딩하고 읽기 전용으로 설정
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind # 호스트 시스템의 Logstash 파이프라인 구성을 컨테이너 내부로 바인딩하고 읽기 전용으로 설정
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"  # 호스트의 5000번 TCP 포트를 Logstash 컨테이너의 5000번 TCP 포트에 매핑 (TCP 프로토콜을 통해 수신되는 로그 처리)
      - "5000:5000/udp"  # 호스트의 5000번 UDP 포트를 Logstash 컨테이너의 5000번 UDP 포트에 매핑 (UDP 프로토콜을 통해 수신되는 로그 처리)
      - "9600:9600"  # 호스트의 9600번 HTTP 포트를 Logstash 컨테이너의 9600번 HTTP 포트에 매핑 (호스트 시스템에서 Logstash의 모니터링 및 관리 인터페이스에 접근
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"  # Logstash JVM의 최대 힙 크기와 최소 힙 크기 설정
    networks:
      - elk  # elk 네트워크에 서비스 연결
    depends_on:
      - elasticsearch  # Elasticsearch 서비스를 먼저 실행한 후 Logstash를 실행하도록 설정

  kibana:
    image: kibana:7.17.10
    volumes:
      - type: bind # 호스트 시스템의 Kibana 구성 파일을 컨테이너 내부로 바인딩하고 읽기 전용으로 설정
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"  # 호스트의 5601번 포트를 Kibana 컨테이너의 5601번 포트에 매핑 (호스트 시스템에서 Kibana의 웹 인터페이스에 접근)
    networks:
      - elk  # elk 네트워크에 서비스 연결
    depends_on:
      - elasticsearch  # Elasticsearch 서비스를 먼저 실행한 후 Kibana를 실행하도록 설정

networks:
  elk:
    driver: bridge  # elk 네트워크를 bridge 드라이버로 설정

volumes:
  elasticsearch:  # Elasticsearch 데이터를 저장하기 위한 Docker 볼륨 정의